### ISSUE TITLE
如何从中间开始下载？

### ISSUE THREAD

**Issue by scavin** [XavierXuV5/manga#2]
Hi 请问如何从之前被中断的下载继续下载？

似乎只能单章下载或全部下载，我想从 40 章开始下载，之前的进程意外掉段了，以及 Windows 下会出现 Chrome 不会关闭，留下一个新标签页。

**Comment by XavierXuV5** [comment]
@scavin 您好。不好意思，现在才看到。由于学业繁忙，暂时没有时间维护这个项目。我尽可能挤出时间来开发，您也可以拉项目下来自行更改开发。

**Comment by scavin** [comment]
感谢回复，我[已经](https://meta.appinn.net/t/topic/36390)用 https://github.com/reseelies/maofly_spider 解决了问题，不过你推荐的 [Epub Manga Create](https://wing-kai.github.io/epub-manga-creator/) 非常好用。

**Comment by XavierXuV5** [comment]
@scavin 感谢您的推荐
